#!/usr/bin/env python3

from sys import argv
from math import sqrt


def read_file(file_name):
    """
    Function to read numbers from file: one on each line
    """

    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()

    factor = []

    for line in lines:
        factor.append(int(line))

    return (factor)

def factorise(n):
    """
    Function to find factors of current number
    """
    for i in range(2, n + 1):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break

def factors(ls):
    """
    Function to iterate between numbers in file
    """

    for i in ls:
        factorise(i)

if len(argv) == 2:
    factors(read_file(argv[1]))
